# Generated by Django 4.0.1 on 2022-02-08 20:41

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='JobClassification',
            fields=[
                ('created', models.DateTimeField(editable=False, null=True)),
                ('updated', models.DateTimeField(editable=False, null=True)),
                ('name', models.CharField(max_length=100, primary_key=True, serialize=False)),
                ('code', models.CharField(max_length=20)),
            ],
            options={
                'verbose_name': 'job classification',
                'verbose_name_plural': 'job classifications',
                'db_table': 'jobs_job_classification',
                'ordering': ['code'],
                'abstract': False,
            },
        ),
    ]
