# Generated by Django 3.2.5 on 2021-11-22 19:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('job_classification', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='jobclassification',
            options={'ordering': ['code'], 'verbose_name': 'classification', 'verbose_name_plural': 'classifications'},
        ),
    ]
