# Generated by Django 3.2.5 on 2021-11-22 03:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('organization', '0001_initial'),
        ('job_source', '0001_initial'),
        ('location', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Job',
            fields=[
                ('created', models.DateTimeField(editable=False, null=True)),
                ('updated', models.DateTimeField(editable=False, null=True)),
                ('id', models.CharField(editable=False, max_length=64, primary_key=True, serialize=False)),
                ('name', models.CharField(editable=False, max_length=256)),
                ('external_id', models.CharField(max_length=256)),
                ('url', models.URLField(max_length=256)),
                ('department', models.ForeignKey(editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='job_department', to='organization.organization')),
                ('locations', models.ManyToManyField(related_name='job_relations', to='location.Location')),
                ('organization', models.ForeignKey(editable=False, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='job_relation', to='organization.organization')),
                ('source', models.ForeignKey(editable=False, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='job_relation', to='job_source.jobsource')),
            ],
            options={
                'verbose_name': 'job',
                'verbose_name_plural': 'jobs',
                'db_table': 'jobs_job',
                'ordering': ['source__name', 'name'],
                'abstract': False,
                'unique_together': {('source', 'external_id')},
            },
        ),
    ]
