# Generated by Django 3.2.5 on 2021-11-22 04:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('job_classification', '0001_initial'),
        ('job', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='job',
            name='application_close_date',
            field=models.DateTimeField(null=True),
        ),
        migrations.AddField(
            model_name='job',
            name='benefits',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='job',
            name='benefits_url',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='job',
            name='classifications',
            field=models.ManyToManyField(related_name='job_relations', to='job_classification.JobClassification'),
        ),
        migrations.AddField(
            model_name='job',
            name='description',
            field=models.TextField(default=''),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='job',
            name='duties',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='job',
            name='education',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='job',
            name='end_date',
            field=models.DateTimeField(null=True),
        ),
        migrations.AddField(
            model_name='job',
            name='evaluations',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='job',
            name='how_to_apply',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='job',
            name='other_information',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='job',
            name='publication_date',
            field=models.DateTimeField(null=True),
        ),
        migrations.AddField(
            model_name='job',
            name='qualifications',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='job',
            name='required_documents',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='job',
            name='requirements',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='job',
            name='start_date',
            field=models.DateTimeField(null=True),
        ),
        migrations.AddField(
            model_name='job',
            name='what_to_expect',
            field=models.TextField(null=True),
        ),
    ]
