# Generated by Django 4.0.7 on 2022-10-11 07:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('job_classification', '0001_initial'),
        ('location', '0002_alter_location_name'),
        ('job_source', '0001_initial'),
        ('organization', '0002_alter_organization_locations_alter_organization_name_and_more'),
        ('job', '0002_alter_job_benefits_url_alter_job_url'),
    ]

    operations = [
        migrations.AlterField(
            model_name='job',
            name='job_classifications',
            field=models.ManyToManyField(related_name='%(data_name)s', to='job_classification.jobclassification'),
        ),
        migrations.AlterField(
            model_name='job',
            name='job_source',
            field=models.ForeignKey(editable=False, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='%(data_name)s', to='job_source.jobsource'),
        ),
        migrations.AlterField(
            model_name='job',
            name='locations',
            field=models.ManyToManyField(related_name='%(data_name)s', to='location.location'),
        ),
        migrations.AlterField(
            model_name='job',
            name='name',
            field=models.CharField(max_length=256),
        ),
        migrations.AlterField(
            model_name='job',
            name='organization',
            field=models.ForeignKey(editable=False, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='%(data_name)s', to='organization.organization'),
        ),
    ]
