# Generated by Django 3.2.5 on 2021-11-29 01:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('job', '0003_alter_job_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='job',
            name='drug_test_required',
            field=models.BooleanField(null=True),
        ),
        migrations.AddField(
            model_name='job',
            name='openings',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='job',
            name='relocation_expenses_reimbursed',
            field=models.BooleanField(null=True),
        ),
        migrations.AddField(
            model_name='job',
            name='supervisory_status',
            field=models.BooleanField(null=True),
        ),
        migrations.AddField(
            model_name='job',
            name='telework_eligible',
            field=models.BooleanField(null=True),
        ),
        migrations.AddField(
            model_name='job',
            name='travel_requirements',
            field=models.TextField(null=True),
        ),
    ]
