# Generated by Django 3.2.5 on 2021-11-29 13:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('job', '0004_auto_20211128_2007'),
    ]

    operations = [
        migrations.AlterField(
            model_name='job',
            name='benefits_url',
            field=models.URLField(null=True),
        ),
    ]
