# Generated by Django 3.2.5 on 2021-12-03 12:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('job_source', '0003_alter_jobsource_options'),
        ('job', '0005_alter_job_benefits_url'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='job',
            options={'ordering': ['job_source__name', 'name'], 'verbose_name': 'job', 'verbose_name_plural': 'jobs'},
        ),
        migrations.RenameField(
            model_name='job',
            old_name='classifications',
            new_name='job_classifications',
        ),
        migrations.RenameField(
            model_name='job',
            old_name='source',
            new_name='job_source',
        ),
        migrations.AlterUniqueTogether(
            name='job',
            unique_together={('job_source', 'external_id')},
        ),
    ]
