# Generated by Django 4.0.1 on 2022-02-09 02:55

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='JobSource',
            fields=[
                ('created', models.DateTimeField(editable=False, null=True)),
                ('updated', models.DateTimeField(editable=False, null=True)),
                ('name', models.CharField(max_length=100, primary_key=True, serialize=False)),
            ],
            options={
                'verbose_name': 'job source',
                'verbose_name_plural': 'job sources',
                'db_table': 'jobs_job_source',
                'ordering': ['name'],
                'abstract': False,
            },
        ),
    ]
