# Generated by Django 3.2.5 on 2021-11-22 03:13

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='JobSource',
            fields=[
                ('created', models.DateTimeField(editable=False, null=True)),
                ('updated', models.DateTimeField(editable=False, null=True)),
                ('id', models.CharField(editable=False, max_length=64, primary_key=True, serialize=False)),
                ('name', models.CharField(editable=False, max_length=256)),
            ],
            options={
                'verbose_name': 'job source',
                'verbose_name_plural': 'job sources',
                'db_table': 'jobs_job_source',
                'ordering': ['name'],
                'abstract': False,
            },
        ),
    ]
