# Generated by Django 3.2.5 on 2021-11-22 19:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('job_source', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='jobsource',
            options={'ordering': ['name'], 'verbose_name': 'source', 'verbose_name_plural': 'sources'},
        ),
    ]
