# Generated by Django 3.2.5 on 2021-11-30 05:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('job_source', '0002_alter_jobsource_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='jobsource',
            options={'ordering': ['name'], 'verbose_name': 'job source', 'verbose_name_plural': 'job sources'},
        ),
    ]
