# Generated by Django 4.0.1 on 2022-02-08 20:41

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Location',
            fields=[
                ('created', models.DateTimeField(editable=False, null=True)),
                ('updated', models.DateTimeField(editable=False, null=True)),
                ('id', models.CharField(editable=False, max_length=64, primary_key=True, serialize=False)),
                ('name', models.CharField(editable=False, max_length=256)),
                ('country', models.CharField(max_length=256)),
                ('province', models.CharField(max_length=256, null=True)),
                ('city', models.CharField(max_length=256)),
                ('longitude', models.FloatField(null=True)),
                ('latitude', models.FloatField(null=True)),
            ],
            options={
                'verbose_name': 'location',
                'verbose_name_plural': 'locations',
                'db_table': 'jobs_location',
                'ordering': ['country', 'province', 'city'],
                'abstract': False,
                'unique_together': {('country', 'province', 'city')},
            },
        ),
    ]
