# Generated by Django 3.2.5 on 2021-11-22 19:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('location', '0002_location_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='location',
            name='province',
            field=models.CharField(max_length=256, null=True),
        ),
    ]
