# Generated by Django 3.2.5 on 2021-11-30 13:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('location', '0003_alter_location_province'),
    ]

    operations = [
        migrations.AddField(
            model_name='location',
            name='generated_id',
            field=models.CharField(default=None, max_length=256),
            preserve_default=False,
        ),
    ]
